inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6

ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false