inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - 'apps/api/application.rb'

ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false
